# Diagnóstico preliminar da qualidade dos dados, incluindo shape, nulos, tipos e duplicados.

In [1]:
from pipelines.readers.pipelines.b3_enriquecimento_cadastral_ativos.reader_parquet_cvm import ReaderSnapshotParquet as b3_cad

empresas.parquet

In [2]:
df = b3_cad(file_identifiers="empresas.parquet").read()

In [3]:
df.tail(3)

,issuingCompany,companyName,tradingName,cnpj,industryClassification,industryClassificationEng,activity,website,hasQuotation,status,...,institutionCommon,institutionPreferred,code,codeCVM,lastDate,hasEmissions,hasBDR,typeBDR,describleCategoryBVMF,dateQuotation
344,MBRF,MARFRIG GLOBAL FOODS S.A.,MARFRIG,03853896000140,Consumo não Cíclico / Alimentos Processados / ...,<NA>,Produção e distribuição de alimentos à base de...,www.marfrig.com.br,S,A,...,BRADESCO,BRADESCO,MBRF3,20788,2026-08-28 23:29:17,False,False,<NA>,<NA>,2007-06-28
345,FRAS,FRASLE MOBILITY S.A.,FRAS-LE,88610126000129,Bens Industriais / Material de Transporte / Ma...,<NA>,Fabricação de peças e acessórios para o sistem...,http://ri.fras-le.com.br,S,A,...,ITAU CORRETORA ACOES,ITAU CORRETORA ACOES,FRAS3,6211,2026-08-28 23:21:42,False,False,<NA>,<NA>,2002-10-01
346,DOHL,DOHLER S.A.,DOHLER,84683408000103,Consumo Cíclico / Tecidos. Vestuário e Calçado...,<NA>,Tecelagem de Fios de Algodão e Fibras sintéticas,www.dohler.com.br,S,A,...,BRADESCO,BRADESCO,DOHL4,5207,2026-08-28 23:18:10,False,False,<NA>,<NA>,1981-09-16

In [4]:
df.shape

(347, 22)

In [5]:
df.isnull().sum()

issuingCompany                 0
companyName                    0
tradingName                    0
cnpj                           0
industryClassification         0
industryClassificationEng    347
activity                      17
website                        0
hasQuotation                   0
status                         0
marketIndicator                0
market                         0
institutionCommon              0
institutionPreferred           0
code                           0
codeCVM                        0
lastDate                       0
hasEmissions                   0
hasBDR                         0
typeBDR                      347
describleCategoryBVMF        347
dateQuotation                  3
dtype: int64

In [6]:
df.dtypes

issuingCompany               string[python]
companyName                  string[python]
tradingName                  string[python]
cnpj                         string[python]
industryClassification       string[python]
industryClassificationEng    string[python]
activity                     string[python]
website                      string[python]
hasQuotation                 string[python]
status                       string[python]
marketIndicator              string[python]
market                       string[python]
institutionCommon            string[python]
institutionPreferred         string[python]
code                         string[python]
codeCVM                      string[python]
lastDate                     datetime64[ns]
hasEmissions                        boolean
hasBDR                              boolean
typeBDR                      string[python]
describleCategoryBVMF        string[python]
dateQuotation                datetime64[ns]
dtype: object

In [7]:
key_cols = df.columns.tolist()
duplicados = df[df.duplicated(subset=key_cols, keep=False)]
print(len(duplicados))

0

codigos.parquet

In [8]:
df = b3_cad(file_identifiers="codigos.parquet").read()

In [9]:
df.tail(3)

      code          isin codeCVM
519  FRAS3  BRFRASACNOR0    6211
520  DOHL3  BRDOHLACNOR2    5207
521  DOHL4  BRDOHLACNPR9    5207

In [10]:
df.shape

(522, 3)

In [11]:
df.isnull().sum()

code       0
isin       0
codeCVM    0
dtype: int64

In [12]:
df.dtypes

code       string[python]
isin       string[python]
codeCVM    string[python]
dtype: object

In [13]:
key_cols = df.columns.tolist()
duplicados = df[df.duplicated(subset=key_cols, keep=False)]
print(len(duplicados))

0

In [14]:
df[df["codeCVM"] == "12653"]

      code          isin codeCVM
23   KLBN3  BRKLBNACNOR2   12653
24   KLBN4  BRKLBNACNPR9   12653
25  KLBN11  BRKLBNCDAM18   12653