In [ ]:
from pipelines.readers.cvm_formulario_demonstracoes_financeiras_padronizadas import ReaderCVMFormularioDemonstracoesFinanceirasPadronizadas

reader_dfp = ReaderCVMFormularioDemonstracoesFinanceirasPadronizadas()
reader_dfp = reader_dfp.read(ticker="VALE3", tipo_arquivo="BPA_con")

In [4]:
from pipelines.readers.cvm_balanco_patrimonial import ReaderCVMBalancoPatrimonial

reader_balanco = ReaderCVMBalancoPatrimonial()

df = reader_balanco.read(ticker="VALE3", tipo_arquivo="BPA_con", cd_conta="1")

df

         Date  VALE_S.A._Ativo_Total
0  2011-03-31            217320211.0
1  2011-03-31            217320211.0
2  2011-06-30            222235600.0
3  2011-06-30            222235600.0
4  2011-09-30            239097330.0
..        ...                    ...
87 2025-06-30            493226000.0
88 2025-09-30            484953000.0
89 2025-09-30            484953000.0
90 2026-03-31            457173000.0
91 2026-03-31            457173000.0

[92 rows x 2 columns]

In [1]:
from research.quant.teste import A

A()

ASDASDASDA

In [1]:
from pipelines.readers.b3_indices_segmentos_setoriais import ReaderB3IndicesSegmentosSetoriais

reader = ReaderB3IndicesSegmentosSetoriais()

reader.read(indice="IDIV")

,Indice,Data Referencia,Código,Ação,Tipo,Qtde. Teórica,Part. (%)
0,IDIV,2026-07-06,ABCB4,ABC BRASIL,PN EJS N2,97361003,0.432
1,IDIV,2026-07-06,ALOS3,ALLOS,ON NM,590258296,3.103
2,IDIV,2026-07-06,AXIA3,AXIA ENERGIA,ON NM,361318461,3.636
3,IDIV,2026-07-06,BRSR6,BANRISUL,PNB N1,249810128,0.647
4,IDIV,2026-07-06,BBSE3,BBSEGURIDADE,ON NM,760086076,5.477
5,IDIV,2026-07-06,BRBI11,BR PARTNERS,UNT N2,58263812,0.158
6,IDIV,2026-07-06,BBDC3,BRADESCO,ON EJ N1,1398110000,4.072
7,IDIV,2026-07-06,BBDC4,BRADESCO,PN EJ N1,1141114941,3.824
8,IDIV,2026-07-06,BRAP4,BRADESPAR,PN N1,309480286,1.294
9,IDIV,2026-07-06,SAUD3,BRADSAUDE,ON EJ NM,310493238,0.846
10,IDIV,2026-07-06,BBAS3,BRASIL,ON NM,1118618972,4.167
11,IDIV,2026-07-06,CXSE3,CAIXA SEGURI,ON NM,740044986,2.833
12,IDIV,2026-07-06,CMIG4,CEMIG,PN N1,2348480832,4.830
13,IDIV,2026-07-06,CSMG3,COPASA,ON NM,443511150,5.136
14,IDIV,2026-07-06,CPFE3,CPFL ENERGIA,ON NM,231550872,1.972
15,IDIV,2026-07-06,CMIN3,CSNMINERACAO,ON N2,2030830634,1.632
16,IDIV,2026-07-06,CURY3,CURY S/A,ON NM,198564222,1.293
17,IDIV,2026-07-06,DIRR3,DIRECIONAL,ON NM,403437491,1.074
18,IDIV,2026-07-06,EGIE3,ENGIE BRASIL,ON NM,440709724,2.641
19,IDIV,2026-07-06,EVEN3,EVEN,ON NM,228591736,0.242
20,IDIV,2026-07-06,EZTC3,EZTEC,ON NM,149508932,0.374
21,IDIV,2026-07-06,FESA4,FERBASA,PN N1,181813759,0.201
22,IDIV,2026-07-06,FLRY3,FLEURY,ON NM,551519540,1.616
23,IDIV,2026-07-06,GRND3,GRENDENE,ON NM,292153931,0.206
24,IDIV,2026-07-06,RANI3,IRANI,ON NM,123879549,0.183
25,IDIV,2026-07-06,ISAE4,ISA ENERGIA,PN N1,512565977,2.642
26,IDIV,2026-07-06,ITSA4,ITAUSA,PN N1,2010855574,5.099
27,IDIV,2026-07-06,ITUB3,ITAUUNIBANCO,ON EJ N1,562595116,4.667
28,IDIV,2026-07-06,ITUB4,ITAUUNIBANCO,PN EJ N1,521752373,4.158
29,IDIV,2026-07-06,JHSF3,JHSF PART,ON ED NM,321575567,0.661
30,IDIV,2026-07-06,KEPL3,KEPLER WEBER,ON NM,213481636,0.260
31,IDIV,2026-07-06,LAVV3,LAVVI,ON NM,91556058,0.198
32,IDIV,2026-07-06,LOGG3,LOG COM PROP,ON NM,63561501,0.335
33,IDIV,2026-07-06,POMO3,MARCOPOLO,ON N2,251400256,0.261
34,IDIV,2026-07-06,POMO4,MARCOPOLO,PN N2,898249634,0.998
35,IDIV,2026-07-06,MBRF3,MARFRIG,ON NM,938839988,2.937
36,IDIV,2026-07-06,LEVE3,METAL LEVE,ON NM,65205210,0.398
37,IDIV,2026-07-06,PGMN3,PAGUE MENOS,ON NM,374821306,0.261
38,IDIV,2026-07-06,PETR3,PETROBRAS,ON N2,538206868,4.254
39,IDIV,2026-07-06,PETR4,PETROBRAS,PN N2,634203386,4.523
40,IDIV,2026-07-06,RECV3,PETRORECSA,ON NM,338724631,0.609
41,IDIV,2026-07-06,PINE4,PINE,PN N2,87086752,0.199
42,IDIV,2026-07-06,SLCE3,SLC AGRICOLA,ON NM,271847703,0.649
43,IDIV,2026-07-06,SYNE3,SYN PROP TEC,ON NM,73241311,0.058
44,IDIV,2026-07-06,TAEE11,TAESA,UNT N2,269583876,2.064
45,IDIV,2026-07-06,TGMA3,TEGMA,ON NM,39462553,0.227
46,IDIV,2026-07-06,TIMS3,TIM,ON NM,881529535,3.747
47,IDIV,2026-07-06,UNIP6,UNIPAR,PNB,61033196,0.683
48,IDIV,2026-07-06,VALE3,VALE,ON ATZ NM,286405277,4.210
49,IDIV,2026-07-06,VLID3,VALID,ON NM,93529802,0.310
50,IDIV,2026-07-06,VBBR3,VIBRA,ON NM,590338439,3.344
51,IDIV,2026-07-06,VULC3,VULCABRAS,ON NM,136437999,0.359